### ISSUE TITLE
USB Printer

### ISSUE THREAD

**Issue by mungle** [exciting-io/printer#52]
Hello! I get this tiny printer from adafruit (https://www.adafruit.com/products/2751) that have USB connection too but I'm unable to make it works with your project... I edited the /boot/cmdline.txt line changing kgdboc=ttyAMA0,19200 to kgdboc=ttyUSB0,19200 but it didn't works!
Any help?

**Comment by mungle** [comment]
Solved editing the pi-printer.rb
In the first lines you can find _ttyAMA0_. Change to _ttyUSB0_.
Scrolling you can find _def serial_ here change the serial number

**Comment by lazyatom** [comment]
You should also be able to provide your custom serial port file descriptor as an argument to `Printer.new` [here](https://github.com/exciting-io/printer/blob/624d8d0a4ac5a70ea2ad4f6a6b3c599b2a0a8a78/pi-printer.rb#L143). :)
